---
title: "DataVis Final Project"
author: "Emil Zetterquist"
date: "3/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(shiny)
library(plotly)
library(shinydashboard)
library(fmsb)

players_df <- read_csv("Data/skaters.csv")
goalies_df <- read_csv("Data/goalies.csv")
teams_df <- read_csv("Data/teams.csv")
```


```{r}
players_df <- players_df %>%
  mutate(minutes_icetime = icetime/60,
         ice_per_game = minutes_icetime/games_played)

top_10 <- all_df %>% 
  arrange(-ice_per_game) %>%
  slice(1:10) %>%
  mutate(name = fct_reorder(name, ice_per_game))

####################################################

radarchart

```

```{r}
var_choice <- names(players_df)
var_choice_g <- names(goalies_df)
var_choice_t <- names(teams_df)

### APP

ui <- dashboardPage(
  dashboardHeader(title = "Hockey"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Players", tabName = "players", icon = icon("ice-skate")),
      menuItem("Goalies", tabName = "goalies", icon = icon("hockey-mask")),
      menuItem("Teams", tabName = "teams", icon = icon("hockey-sticks"))
    )
  ),
  dashboardBody(
    tabItems(
      tabItem("players",
              box(selectizeInput("stat",
                                 label = "Choose a Statistic",
                                 choices = var_choice,
                                 selected = "ice_per_game"), 
                  height = 82
                  ),
              box(radioButtons("situation",
                               label = "Situation",
                               choices = levels(factor(players_df$situation)),
                               selected = "all",
                               inline = TRUE
                               )
                  ),
              box(plotlyOutput(outputId = "plot1"), width = 8),
      ),
      tabItem("goalies",
              box(selectizeInput("goaliestat",
                                 label = "Choose a Statistic",
                                 choices = var_choice,
                                 selected = "games_played"),
                  height = 82
                  ),
              box(radioButtons("sitgoalie",
                               label = "Situation",
                               choices = levels(factor(goalies_df$situation)),
                               selected = "all",
                               inline = TRUE
                               )
              ),
              box(plotlyOutput(outputId = "plot2"), width = 8)
      ),
      tabItem("teams",
              box(selectizeInput("teamstat",
                                 label = "Choose a Statistic",
                                 choices = var_choice_t,
                                 selected = "goalsFor"),
                  height = 82
                  ),
              box(radioButtons("sitteam",
                               label = "Situation",
                               choices = levels(factor(teams_df$situation)),
                               selected = "all",
                               inline = TRUE)
                  ),
              box(plotlyOutput(outputId = "plot3"), width = 8)
      )
    )
  )
)

server <- function(input, output, session) {
  
  ## Players
  
  top_10_react <- reactive({
    players_df %>% 
      filter(situation == input$situation) %>%
      arrange(desc(.data[[input$stat]])) %>%
      slice(1:10) %>%
      mutate(name = fct_reorder(name, .data[[input$stat]]))
  })
  
  output$plot1 <- renderPlotly({
    p1 <- ggplot(data = top_10_react(), aes(y = name, 
                                            x = .data[[input$stat]],
                                            text = .data[[input$stat]])) +
      geom_point(colour = "blue",
                 size = 2.5) +
      labs(y = "")
    
    ggplotly(p1,
             tooltip = "text",
             displayModeBar = FALSE)
  })
  
  ## Goalies
  
  top_10_goalies <- reactive({
    goalies_df %>% 
      filter(situation == input$sitgoalie) %>%
      arrange(desc(.data[[input$goaliestat]])) %>%
      slice(1:10) %>%
      mutate(name = fct_reorder(name, .data[[input$goaliestat]]))
  })
  
  output$plot2 <- renderPlotly({
    p2 <- ggplot(data = top_10_goalies(), aes(y = name, 
                                            x = .data[[input$goaliestat]],
                                            text = .data[[input$goaliestat]])) +
      geom_point(colour = "blue",
                 size = 2.5) +
      labs(y = "")
    
    ggplotly(p2,
             tooltip = "text",
             displayModeBar = FALSE)
  })
  
  ## Teams
  
  top_10_teams <- reactive({
    teams_df %>% 
      filter(situation == input$sitteam) %>%
      arrange(desc(.data[[input$teamstat]])) %>%
      slice(1:10) %>%
      mutate(name = fct_reorder(name, .data[[input$teamstat]]))
  })
  
  output$plot3 <- renderPlotly({
    p3 <- ggplot(data = top_10_teams(), aes(y = name, 
                                            x = .data[[input$teamstat]],
                                            text = .data[[input$teamstat]])) +
      geom_point(colour = "blue",
                 size = 2.5) +
      labs(y = "")
    
    ggplotly(p3,
             tooltip = "text",
             displayModeBar = FALSE)
  })
  
}

shinyApp(ui, server)

```

```{r}
shots_df <- goalies_df %>%
  filter(name == "Jacob Markstrom") %>%
  filter(situation == "5om5") %>%
  select(lowDangerShots, mediumDangerShots, highDangerShots)

radarchart(shots_df,
           cglty = 1, cglcol = "gray",
           pcol = 4, plwd = 2,
           pfcol = rgb(0, 0.4, 1, 0.25))
```

```{r}
teamstats17_df <- read_csv("Data/teamstatstotals/teamstatstotals16-17.csv")
teamstats18_df <- read_csv("Data/teamstatstotals/teamstatstotals17-18.csv")
teamstats19_df <- read_csv("Data/teamstatstotals/teamstatstotals18-19.csv")
teamstats20_df <- read_csv("Data/teamstatstotals/teamstatstotals19-20.csv")
teamstats21_df <- read_csv("Data/teamstatstotals/teamstatstotals20-21.csv")
teamstats22_df <- read_csv("Data/teamstatstotals/teamstatstotals21-22.csv")

teamstats17_df <- teamstats17_df %>% mutate(season = '16/17')
teamstats18_df <- teamstats18_df %>% mutate(season = '17/18') 
teamstats19_df <- teamstats19_df %>% mutate(season = '18/19')
teamstats20_df <- teamstats20_df %>% mutate(season = '19/20')
teamstats21_df <- teamstats21_df %>% mutate(season = '20/21')
teamstats22_df <- teamstats22_df %>% mutate(season = '21/22')

teams_full <- rbind(teamstats17_df,
                    teamstats18_df,
                    teamstats19_df,
                    teamstats20_df, 
                    teamstats21_df,
                    teamstats22_df) %>%
  select(season, everything())

teams_full <- teams_full %>%
  group_by(season) %>%
  mutate(ff_rate = FF/TOI,
         cf_rate = CF/TOI,
         cf_total = sum(CF),
         total_TOI = sum(TOI),
         TOI_pg = (TOI/GP)*60,
         n_teams = n(),
         ppg = Points/GP)

## Total Attempts
teams_2021 <- teams_full %>% 
  filter(season == '20/21') %>%
  mutate(Team = fct_reorder(.f = Team, .x = CF))

  ggplot(data = teams_full, aes(x = Team,
                                y = CF)) +
  geom_bar(stat = "identity") +
    labs(x = "", y = "Corsi for") +
    coord_flip()
  
## CF_rate
  
teams_2122 <- teams_full %>%
  filter(season == '20/21') %>%
  mutate(Team = fct_reorder(.f = Team, .x = cf_rate)) 

ggplot(data = teams_2122, aes(x = Team,
                              y = cf_rate)) +
  geom_bar(stat = "identity") +
  labs(x = "", y = "Corsi for per Minute") +
  coord_flip()

## Plotting cf_rate against points

teams_full %>% 
  filter(season == '20/21') %>%
  ggplot(aes(x = cf_rate, y = ppg)) +
  geom_point() +
  geom_smooth(method = lm)
```

